command:
  #Hora 
  - command:
    input: Que horas são?
    entity: time
    action: getTime
  - command:
    input: Me diga as horas.
    entity: time
    action: getTime
  - command:
    input: Eu quero saber as horas.
    entity: time
    action: getTime  
  #Data    
  - command:
    input: Qual é a data de hoje?
    entity: time
    action: getDate
  - command:
    input: Data de hoje.
    entity: time
    action: getDate  
  - command:
    input: que dia e hoje?.
    entity: time
    action: getDate   
  # Tempo
  - command:
    input: Previsão do tempo
    entity: Weather 
    action: getWeather
  - command:
    input: Como está o clima?
    entity: Weather
    action: getWeather   
  #Open
  - command:
    input: Abrir bloco de notas
    entity: notepad
    action: open
# - command:
#    input: Abrir google
#    entity: chrome
#    action: open 
  
  #apresentação
  - command:
    input: oi
    entity: ola
    action: gethello
  - command:
    input: olá
    entity: ola
    action: gethello  
  - command:
    input: olá, Boa tarde
    entity: ola
    action: gethello
  - command:
    input: olá, Boa noite
    entity: ola
    action: gethello    
  - command:
    input: olá, bom dia
    entity: ola
    action: gethello 
  #criação  
  - command:
    input: quem são seus criadores 
    entity: ola
    action: gethello 
  - command:
    input: em qual linguagem de programação você foi desenvolvida?
    entity: cria
    action: getlingua 

  #nada
  - command:
    input: a b abistrato
    entity:  nome 
    action:  nome  


  - command:
    input: Não entendi
    entity: não_entendido
    action: responder_não_entendido

#elogios
- command:
    input: você e muito bonita 
    entity: bonita
    action: getbonita
    